services:
  _defaults:
    autoconfigure: true
    autowire: true
    public: true

  App\Presentation\PlaygroundController:
    public: true
    autoconfigure: true
    class: "App\Presentation\PlaygroundController"
