doctrine_migrations:
  migrations_paths:
    'Application\Migrations': '%kernel.project_dir%/app/DoctrineMigrations'
  storage:
    table_storage:
      table_name: migration_versions
      executed_at_column_name: executed_at
  connection: default
  all_or_nothing: true
  organize_migrations: false
