fos_rest:
  disable_csrf_role: ROLE_API
  param_fetcher_listener: true
  view:
    view_response_listener: false
    formats:
      json: true
      xml: false
      jsonp: false
      rss: false
      html: false
  routing_loader:
    default_format: json
  zone:
    - { path: ^/api/* }
  format_listener:
    enabled: true
    rules:
      - { path: '^/api/docs', methods: [ GET ], priorities: [ 'html' ], fallback_format: html }
      - { path: '^/api', priorities: [ 'json' ], fallback_format: 'json', prefer_extension: false }
      - { path: '^/', priorities: [ 'html', '*/*' ], fallback_format: html, prefer_extension: true }
  exception:
    flatten_exception_format: legacy
    serializer_error_renderer: true
    map_exception_codes: true
  body_listener: true
  serializer:
    serialize_null: true
