nelmio_cors:
  defaults:
    allow_credentials: true
    allow_origin: ['*']
    allow_headers: ['*']
    allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'OPTIONS']
    max_age: 3600
    origin_regex: false
  paths:
    '^/':
      allow_origin: ['*']
