security:
  # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
  providers:
    user_db_admin:
      entity:
        class: App\Domain\User\Entity\AdminUser
        property: email
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    api:
      pattern: ^/api
      stateless: true
      anonymous: true
    admin:
      pattern: ^/admin(.*)
      context: user
      anonymous: ~
      form_login:
        provider: user_db_admin
        login_path: /admin/login
        check_path: /admin/login
        use_forward: false
        default_target_path: /admin
        always_use_default_target_path: true
        csrf_token_generator: security.csrf.token_manager
        csrf_parameter: _csrf_token
        csrf_token_id: authenticate_admin
      logout:
        path: admin_security_logout
      switch_user: false
  encoders:
    Symfony\Component\Security\Core\User\User:
      algorithm: bcrypt
      cost: 12
    App\Domain\User\Entity\AdminUser:
      algorithm: auto


    #   Easy way to control access for large sections of your site
    #   Note: Only the *first* access control that matches will be used
  access_control:
    - { path: '^/admin/login$', roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: '^/admin/logout$', roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: '^/admin', roles: ROLE_ADMIN }
