version: '3'

services:
  php:
    container_name: duo-php
    build: ./.docker/php
    depends_on:
      - pgsql
    volumes:
      - ./:/usr/src/app
    user: 1000:1000
    #    ports:
    #      - "80:80"
    environment:
      APP_ENV: dev
      DATABASE_URL: "postgres://postgresql:postgresql@pgsql:5432/duo"
      SENTRY_DSN: "https://3fb864e5f56b4a23ad7807aa22bb9f0d@o390203.ingest.sentry.io/5674563"
      APP_SECRET: "secret"
    networks:
      duo-network:
        ipv4_address: 10.203.0.3
  nginx:
    image: nginx:1.15.3-alpine
    #    restart: on-failure
    depends_on:
      - php
    volumes:
      - './public:/usr/src/app'
      - './.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - "80:80"
    networks:
      duo-network:
        ipv4_address: 10.203.0.6
  pgsql:
    container_name: duo-pgsql
    image: "evang522/duo_db_18_03_2021"
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: postgresql
    networks:
      duo-network:
        ipv4_address: 10.203.0.4
networks:
  duo-network:
    driver: bridge
    ipam:
      config:
        - subnet: "10.203.0.0/24"

# Hosts
